# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: localgoat

builds:
  - binary: lg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    wrap_in_directory: true
    format: zip
    format_overrides:
      - goos: windows
        format: zip  

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: jaz303
    name: localgoat
  draft: false