#!/bin/bash

if [ ! -z "$(git status --porcelain)" ]; then 
    echo "Working directory not clean"
    exit 1
fi

VERSION=$1

if [ -z "${VERSION}" ]; then
    echo "Version must be specified"
    exit 1
fi

rm -rf dist
echo "package main

var localgoatVersion = \"${VERSION}\"
" > version.go

# git add version.go
# git commit -m "v${VERSION}"
# git tag -a "v${VERSION}" -m "Release v${VERSION}"
# git push origin master --tags

# goreleaser release